
= Dynamic Rescheduling of Workloads

ifdef::vmware[]
.Rosetta Stone: VMware
****
この機能は、VMwareの Distributed Resource Scheduler (DRS) に類似しています。

DRSと同様に、OpenShift Descheduler（デスケジューラー）はVM作成に必須の要素ではありませんが、いつでも適用することができます。
****
endif::[]

[#dynamicreschintro]
== Introduction

デスケジューラーを使用すると、特定の戦略に基づいてポッドを立ち退き（Evict）させ、より適切なノードに再スケジュールすることができます。しかし、通常の立ち退きは「停止と起動（再起動）」を伴うため、これを達成するためにVMを再起動させたい人はいません。

OpenShift Virtualizationでは、*virt-api-validator* という *Validating Webhook（検証Webフック）* を使用して、この処理をスムーズに処理します。このWebフックはすべての立ち退き要求をインターセプトし、その要求をどのように処理するかの一連の判断を行います。

簡単に要約すると、ライブマイグレーションが可能な仮想マシンに対して立ち退き要求が受信された場合、そのVMは立ち退きさせられる代わりに、ライブマイグレーションが実行されます。

https://github.com/kubevirt/kubevirt/blob/main/docs/handling-eviction-requests.md[OpenShift Virtualizationにおける立ち退き要求の処理方法]

以下のような状況において、実行中のポッドをデスケジュール（再配置）することのメリットが得られます。

* ノードの利用率が低すぎる（過小利用）、または高すぎる（過剰利用）。
* 補完的な要件（テイントやラベルなど）が変更され、元のスケジューリング決定が特定のノードに対して適切ではなくなった。
* ノードの障害により、ポッドを移動させる必要がある。
* クラスターに新しいノードが追加された。
* ポッドの再起動回数が多すぎる。

[#dynamicreschobj]
== Objectives

このモジュールでは、*KubeVirtRelieveAndMigrate* プロファイルを使用した *Descheduler（デスケジューラー）* の使用プロセスをご案内します。

** このプロファイルは、リソースコストの高いノードからポッドを立ち退かせることで、全体的なリソース費用を削減し、ワークロードのマイグレーションを可能にします。また、定期的にワークロードの再バランスを行うことで、ノード間で同様の余剰容量を維持し、突発的なワークロードの急増（スパイク）への対応力を高めます。ノードは以下のようなコストに直面する可能性があります。

*** リソース利用率：リソースの圧迫が増すと、実行中のアプリケーションのオーバーヘッドが高くなります。
*** ノードのメンテナンス：ノード上のコンテナ数が増えると、リソース消費量とメンテナンスコストが増加します。

[#dynamicreschreq]
== Requirements

* Descheduler Operator がインストールされていること
* *KubeVirtRelieveAndMigrate* プロファイルが構成されていること
* すべてのワーカーノードで PSI メトリクスが有効になっていること

受講者の利便性のため、これらの要件はすべてラボ環境であらかじめ有効化されています。

NOTE: PSI（Pressure Stall Information）は、タスクがCPU、メモリ、またはI/Oリソースを待つために費やした時間を計測・報告するLinuxカーネルの機能であり、リソースの競合や飽和状態を可視化します。プロセスがリソースを待つためにどれだけの時間ストール（失速）したかを定量化し、システムがリソース不足による圧力を受けている時間の割合を示すことで、パフォーマンスのボトルネックを特定するのに役立ちます。

include::lab-access.adoc[]

[#dynamicreschinstructions]
== Instructions

. 画面右側の *ターミナル* ウィンドウから、*admin* ユーザーとして OpenShift CLI にログインしていることを確認し、次のステップに進みます。
+

. *dynamic-schedule-vm-1* 仮想マシンを起動します。

+
[.wrap,console,role=execute]
----
virtctl start dynamic-schedule-vm-1 -n dynamic-schedule
----

+
[source,console]
----
VM dynamic-schedule-vm-1 was scheduled to start
----
+
. *dynamic-schedule* ネームスペースでどの仮想マシンが実行されているかを確認します。

+
[.wrap,console,role=execute,subs="attributes"]
----
oc get vmi -n dynamic-schedule
----
+
[source,console]
----
NAME                    AGE     PHASE     IP             NODENAME                        READY
dynamic-schedule-vm-1   2m41s   Running   10.232.0.240   control-plane-cluster-jlkcx-1   True
----

+
. デスケジューラー（Descheduler）Operator の構成を確認します。

+
[.wrap,console,role=execute,subs="attributes"]
----
oc -n openshift-kube-descheduler-operator get kubedescheduler cluster -o yaml
----

+
[source,yaml,role="wrap",subs="attributes"]
----
apiVersion: operator.openshift.io/v1
kind: KubeDescheduler
metadata:
  name: cluster
  namespace: openshift-kube-descheduler-operator
spec:
  logLevel: Normal
  mode: Predictive
  operatorLogLevel: Normal
  profileCustomizations:
    devEnableSoftTainter: true
    devDeviationThresholds: AsymmetricLow
    devActualUtilizationProfile: PrometheusCPUCombined
  profiles:
    - KubeVirtRelieveAndMigrate
  # This is the interval at which the descheduler will run ; Set a lower value for testing purposes :
  deschedulingIntervalSeconds: 3600
  managementState: Managed
----

+
[NOTE]
====
デフォルトでは、モードが *Predictive（予測）* に設定されています。これは、立ち退き処理の *シミュレーションとログ記録* のみを行うことを意味し、実際の立ち退き（Eviction）は *行われません*。

実際の立ち退きを *有効にする* には、モードを *Automatic（自動）* に設定する必要があります。
====

+
. デスケジューラーのポッドが実行されていることを確認し、*openshift-kube-descheduler-operator* ネームスペースのログを確認します。

+
[.wrap,console,role=execute,subs="attributes"]
----
oc logs -n openshift-kube-descheduler-operator -l app=descheduler
----

+
[,shell,subs="attributes"]
.Output
----
I0102 13:57:26.543545       1 lownodeutilization.go:210] "Node has been classified" category="underutilized" node="worker-cluster-jlkcx-2" usage={"MetricResource":"4"} usagePercentage={"MetricResource":4}
I0102 13:57:26.543656       1 lownodeutilization.go:210] "Node has been classified" category="underutilized" node="worker-cluster-jlkcx-1" usage={"MetricResource":"5"} usagePercentage={"MetricResource":5}
I0102 13:57:26.543667       1 lownodeutilization.go:236] "Node is appropriately utilized" node="control-plane-cluster-jlkcx-1" usage={"MetricResource":"13"} usagePercentage={"MetricResource":13}
I0102 13:57:26.543674       1 lownodeutilization.go:248] "Criteria for a node under utilization" MetricResource="0.00%"
I0102 13:57:26.543687       1 lownodeutilization.go:249] "Number of underutilized nodes" totalNumber=2
I0102 13:57:26.543694       1 lownodeutilization.go:250] "Criteria for a node above target utilization" MetricResource="10.00%"
I0102 13:57:26.543704       1 lownodeutilization.go:251] "Number of overutilized nodes" totalNumber=0
I0102 13:57:26.543709       1 lownodeutilization.go:275] "All nodes are under target utilization, nothing to do here"
I0102 13:57:26.543786       1 profile.go:376] "Total number of evictions/requests" extension point="Balance" evictedPods=0 evictionRequests=0
I0102 13:57:26.543827       1 descheduler.go:403] "Number of evictions/requests" totalEvicted=0 evictionRequests=0
----

+
. デスケジューラーの機能を実証するために、負荷テスト（ストレスストスト）用ポッドをデプロイします。
+
.. 既存の *stress-test* デプロイメントにパッチを適用して *nodeSelector* を使用し、VMが実行されているノードと同じノードでポッドが実行されるようにします。
+
*nodeSelector* のキーである *kubernetes.io/hostname* を動的に設定するために、以下を行います。
+
... すべてのノードを取得する
... *dynamic-schedule-vm-1* VMが実行されている特定のノードで結果をフィルタリングする

+
[.wrap,console,role=execute,subs="attributes"]
----
oc -n dynamic-schedule-stress-test patch deployment stress-test --type merge -p "{\"spec\":{\"template\":{\"spec\":{\"nodeSelector\":{\"kubernetes.io/hostname\":\"$(oc get nodes -o custom-columns=":metadata.name" --no-headers | grep $(oc get vmi dynamic-schedule-vm-1 -n dynamic-schedule -o json | jq -r '.status.nodeName'))\"}}}}}"
----

+
.. デプロイメントをスケール（拡張）します。

+
[.wrap,console,role=execute,subs="attributes"]
----
oc -n dynamic-schedule-stress-test scale deployment stress-test --replicas=1
----

+
.. ポッドが実行中であることを確認します。

+
[.wrap,console,role=execute,subs="attributes"]
----
oc get pods -n dynamic-schedule-stress-test -o wide
----
+
. テスト目的のため、kubedescheduler クラスターリソースを編集して *deschedulingIntervalSeconds* を低い値に設定します。

+
[.wrap,console,role=execute,subs="attributes"]
----
oc -n openshift-kube-descheduler-operator patch kubedescheduler cluster --type merge -p '{"spec":{"deschedulingIntervalSeconds":5}}'
----
. *openshift-kube-descheduler-operator* ネームスペース内のデスケジューラーポッドのログを表示します。

+
[.wrap,console,role=execute,subs="attributes"]
----
oc logs -f -n openshift-kube-descheduler-operator -l app=descheduler
----

+
[source,console]
----
I1113 15:24:57.371043       1 lownodeutilization.go:261] "Number of overutilized nodes" totalNumber=1
I1113 15:24:57.371052       1 nodeutilization.go:174] "Total capacity to be moved" MetricResource=143
I1113 15:24:57.371273       1 nodeutilization.go:189] "Pods on node" node="worker01" allPods=72 nonRemovablePods=45 removablePods=27
I1113 15:30:00.673653       1 nodeutilization.go:205] "Evicting pods based on priority, if they have same priority, they'll be evicted based on QoS tiers"
I1113 15:30:00.673755       1 evictions.go:551] "Evicted pod in dry run mode" pod="dynamic-schedule/virt-launcher-dynamic-schedule-vm-1-lltlv" reason="" strategy="LowNodeUtilization" node="worker01" profile="DevKubeVirtRelieveAndMigrate"
----

+
[NOTE]
====
*virt-launcher-dynamic-schedule-vm-1-lltlv* ポッドが立ち退き（Evict）対象になったことが確認できますが、*Descheduler* がドライラン（Dry run）または *Predictive（予測）* モードであるため、実際には実行されていません。
====

+
. 実際に立ち退きを実行させるため、*Descheduler* のモードを *Automatic（自動）* に設定します。

+
[.wrap,console,role="execute",subs="attributes"]
----
oc -n openshift-kube-descheduler-operator patch kubedescheduler cluster --type merge -p '{"spec":{"mode":"Automatic"}}'
----

+
. openshift-kube-descheduler-operator ネームスペース内のデスケジューラーポッドのログを確認します。
+
[.wrap,console,role="execute",subs="attributes"]
----
oc logs -f -n openshift-kube-descheduler-operator -l app=descheduler
----

+
[,shell,subs="attributes"]
.Output
----
I0102 14:53:47.976452       1 lownodeutilization.go:251] "Number of overutilized nodes" totalNumber=1
I0102 14:53:47.976473       1 nodeutilization.go:185] "Total capacity to be moved" MetricResource=79
I0102 14:53:47.976924       1 nodeutilization.go:200] "Pods on node" node="worker-cluster-jlkcx-2" allPods=44 nonRemovablePods=31 removablePods=13
I0102 14:53:47.976946       1 nodeutilization.go:216] "Evicting pods based on priority, if they have same priority, they'll be evicted based on QoS tiers"
I0102 14:53:47.977036       1 profile.go:376] "Total number of evictions/requests" extension point="Balance" evictedPods=0 evictionRequests=0
I0102 14:53:47.977065       1 descheduler.go:403] "Number of evictions/requests" totalEvicted=0 evictionRequests=0
I0102 14:53:52.963035       1 lownodeutilization.go:210] "Node has been classified" category="overutilized" node="control-plane-cluster-jlkcx-1" usage={"MetricResource":"10"} usagePercentage={"MetricResource":10}
I0102 14:53:52.963113       1 lownodeutilization.go:210] "Node has been classified" category="underutilized" node="worker-cluster-jlkcx-1" usage={"MetricResource":"7"} usagePercentage={"MetricResource":7}
I0102 14:53:52.963143       1 lownodeutilization.go:210] "Node has been classified" category="underutilized" node="worker-cluster-jlkcx-2" usage={"MetricResource":"100"} usagePercentage={"MetricResource":100}
----

+
[NOTE]
====
stress-test ポッドが実行されているノードが過剰利用（Overutilized）ノードとして検出されたことが確認できます。

これにより、VMは自動的に別のノードへマイグレーション（移行）されます。
====

+
. ポッドが立ち退かされ、別のノードに再スケジュールされていることを確認します（立ち退きが発生するまで少し時間がかかる場合があるため、監視用に *-w* パラメーターを使用します）。

+
[.wrap,console,role="execute",subs="attributes"]
----
oc get pods -n dynamic-schedule -o wide -w
----

+
[source,console]
.Output
----
NAME                                        READY   STATUS      RESTARTS   AGE     IP             NODE                            NOMINATED NODE   READINESS GATES
virt-launcher-dynamic-schedule-vm-1-lltlv   0/2     Completed   0          31m     10.232.0.240   control-plane-cluster-jlkcx-1              1/1
virt-launcher-dynamic-schedule-vm-1-n6ct7   2/2     Running     0          2m37s   10.234.0.84    worker-cluster-jlkcx-2                     1/1
----

+
. 立ち退きが正常に機能していることをさらに確認するために、負荷テスト（stress-test）ポッドをVMが現在実行されている新しいノードに移動させ、VMが再度移動するのを監視してみましょう。

+
[.wrap,console,role="execute",subs="attributes"]
----
oc -n dynamic-schedule-stress-test patch deployment stress-test --type merge -p "{\"spec\":{\"template\":{\"spec\":{\"nodeSelector\":{\"kubernetes.io/hostname\":\"$(oc get nodes -o custom-columns=":metadata.name" --no-headers | grep $(oc get vmi dynamic-schedule-vm-1 -n dynamic-schedule -o json | jq -r '.status.nodeName'))\"}}}}}"
----

+
このパッチは *nodeSelector* を変更し、*stress-test* デプロイメントのロールアウトをトリガーして、*dynamic-schedule-vm-1* VMが実行されているノードにポッドを再度プッシュします。

+
[.wrap,console,role="execute",subs="attributes"]
----
oc get pods -n dynamic-schedule -o wide -w
----

+
[,shell,subs="attributes"]
.Output
----
NAME                                        READY   STATUS      RESTARTS   AGE     IP             NODE                            NOMINATED NODE   READINESS GATES
virt-launcher-dynamic-schedule-vm-1-4qhnq   2/2     Running     0          4m28s   10.232.1.70    control-plane-cluster-jlkcx-1              1/1
virt-launcher-dynamic-schedule-vm-1-n6ct7   0/2     Completed   0          9m49s   10.234.0.84    worker-cluster-jlkcx-2                     1/1
----

[IMPORTANT]
====
次のラボ用に十分なリソースを確保するため、*dynamic-schedule-stress-test* デプロイメントをスケールダウンし、*Terminal（ターミナル）* ウィンドウから *virtctl* を使用して *dynamic-schedule-vm-1* VM を停止してください。

[.wrap,console,role=execute,subs="attributes"]
----
oc -n dynamic-schedule-stress-test scale deployment stress-test --replicas=0
----

*deployment.apps/stress-test scaled*

[,shell,role="execute wrap",subs="attributes"]
----
virtctl stop dynamic-schedule-vm-1 -n dynamic-schedule
----

*VM dynamic-schedule-vm-1 was scheduled to stop*
====
